apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dgse.fullname" . }}
  labels:
    {{- include "dgse.labels" . | nindent 4 }}
data:
  DRONE_BIND: {{ .Values.config.DRONE_BIND | b64enc }}
  DRONE_DEBUG: {{ .Values.config.DRONE_DEBUG | b64enc }}
  DRONE_SECRET: {{ .Values.config.DRONE_SECRET | b64enc }}
